In [1]:
import numpy as np

Question 1: Check version of numpy

In [5]:
np.version.version

'1.17.2'

Question 2: How to create a boolean array?

In [8]:
bool1 = np.ones([3,3],dtype=bool)
bool1

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Question 3: How to extract items that satisfy a given condition from 1D array?

In [9]:
ar1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
filteredAr1 = ar1[ar1%2!=0]
filteredAr1

array([1, 3, 5, 7, 9])

Question 4: Replace all odd numbers in arr with -1

In [22]:
ar2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar2[ar2%2!=0] = -1
ar2

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

Question 5: How to replace items that satisfy a condition without affecting the original array?

In [39]:
ar3 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ar4 = np.where(ar3 % 2 != 0, -1, ar3)
print(ar4)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


Question 6: How to stack two arrays vertically?

In [55]:
ar5 = np.arange(10).reshape(2,5)
ar6 = np.arange(20,30,1).reshape(2,5)
print('array 1: ',ar5)
print('\narray 2: ',ar6)
concatentedArr = np.concatenate([ar5,ar6],axis=0) # Here we are suppose to pass the 2 arrays, and the axis along
# which we are expecting to stack. Here row wise stacking we are doing.
print('\nVertically stacked array: ',concatentedArr)

array 1:  [[0 1 2 3 4]
 [5 6 7 8 9]]

array 2:  [[20 21 22 23 24]
 [25 26 27 28 29]]

Vertically stacked array:  [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [20 21 22 23 24]
 [25 26 27 28 29]]


Question 7: How to stack two arrays horizontally?

In [56]:
ar8 = np.arange(10).reshape(2,5)
ar9 = np.arange(20,30,1).reshape(2,5)
print('array 1: ',ar8)
print('\narray 2: ',ar9)
concatentedArr = np.concatenate([ar8,ar9],axis=1) # Here we are suppose to pass the 2 arrays, and the axis along
# which we are expecting to stack. Here column wise stacking we are doing.
print('\nVertically stacked array: ',concatentedArr)

array 1:  [[0 1 2 3 4]
 [5 6 7 8 9]]

array 2:  [[20 21 22 23 24]
 [25 26 27 28 29]]

Vertically stacked array:  [[ 0  1  2  3  4 20 21 22 23 24]
 [ 5  6  7  8  9 25 26 27 28 29]]


Question 8 : How to get the common items between two python numpy arrays?

In [60]:
ar10 = np.array([1,2,3,4,5,6],dtype=int)
ar11 = np.array([7,8,9,5,10,11],dtype=int)
x = np.intersect1d(ar10,ar11)
print(type(x))
print(x)

<class 'numpy.ndarray'>
[5]


Question 9: How to remove from one array those items that exist in another?

In [67]:
ar12 = np.array([1,2,3,4,5,6],dtype=int)
ar13 = np.array([7,8,9,5,10,6],dtype=int)
diff = np.setdiff1d(ar12,ar13)
print(diff)

[1 2 3 4]


Question 10: How to get the positions where elements of two arrays match?

In [70]:
ar14 = np.array([1,2,3,4,5,6],dtype=int)
ar15 = np.array([7,8,9,10,5,6],dtype=int)
np.where(ar14 == ar15)

(array([4, 5]),)

Question 11: How to extract all numbers between a given range from a numpy array?

In [78]:
ar16 = np.array([2, 6, 1, 9, 10, 3, 27])
filteredAr16 = ar16[(ar16>=5) & (ar16<=10)]
filteredAr16

array([ 6,  9, 10])

Question 12: How to swap two columns in a 2d numpy array?

In [82]:
ar17 = np.arange(9).reshape(3,3)
print('Original array: ',ar17)
ar17[:,[1,0,2]]

Original array:  [[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

Question 13: How to swap two columns in a 2d numpy array?

In [83]:
ar18 = np.arange(9).reshape(3,3)
print('Original array: ',ar18)
ar18[[1,0,2],:]

Original array:  [[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])

Question 14: How to reverse the rows of a 2D array?

In [89]:
ar19 = np.arange(9).reshape(3,3)
print('Original array: ',ar19)
ar19[::-1]

Original array:  [[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

Question 15: How to reverse the columns of a 2D array?

In [102]:
ar19 = np.arange(9).reshape(3,3)
print('Original array: ',ar19)
ar19[:,2::-1]

Original array:  [[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

Question 16: Find the mean, median, standard deviation of iris’s sepal length (1st column)

In [111]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

# To get the complete data
data = np.genfromtxt(url, delimiter=',', dtype='object')

# To specifically get only sepal length
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])
print(type(sepallength))

# Mean
meanX = np.mean(sepallength)
medianX = np.median(sepallength)
stdX = np.std(sepallength)
print('Mean: ',meanX)
print('Median: ',medianX)
print('Standard Deviation: ',stdX)

<class 'numpy.ndarray'>
Mean:  5.843333333333334
Median:  5.8
Standard Deviation:  0.8253012917851409


Question 17: How to filter a numpy array based on two or more conditions?

In [127]:
ar20 = np.arange(10).reshape(2,5)
print(ar20)

ar20[(ar20>=3) & (ar20<=7)]

[[0 1 2 3 4]
 [5 6 7 8 9]]


array([3, 4, 5, 6, 7])

Question 18: How to find the correlation between two columns of a numpy array?

In [154]:
ar1 = np.arange(1,11)
ar2 = ar1 + x + np.random.normal(0, 10, 10)
np.corrcoef(ar1,ar2)

array([[1.        , 0.61668505],
       [0.61668505, 1.        ]])

Question 19: How to sort a 2D array by a column

In [165]:
ar21 = np.array([[28,43,80],[93,11,28],[61,94,57]])
print('Original array: ',ar21)
# lets sort the above array using third column (=2)
srtdArray21 = ar21[ar21[:,2].argsort()]
print('\nSorted by column3: ',srtdArray21)

Original array:  [[28 43 80]
 [93 11 28]
 [61 94 57]]

Sorted by column3:  [[93 11 28]
 [61 94 57]
 [28 43 80]]


Question 20: How to generate custom sequences in numpy without hardcoding?

In [172]:
ar22 = np.array([1,2,3,4,5])

# To generate pattern 1,1,1,2,2,2,3,3,3
x = np.repeat(ar22,3)
print('pattern 1: ',x)
# To generate pattern 1,2,3,1,2,3,1,2,3
y = np.tile(ar22,3)
print('pattern 2:',y)

pattern 1:  [1 1 1 2 2 2 3 3 3 4 4 4 5 5 5]
pattern 2: [1 2 3 4 5 1 2 3 4 5 1 2 3 4 5]
